name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run pre-commit
        uses: zeevro/action-pre-commit-uv@main # TODO: Replace with tox-dev/action-pre-commit-uv once PR is merged

  test:
    name: Test ${{ matrix.kind }} on Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.13t']
        kind: [pure-python, native]
        exclude: [{ kind: pure-python, python: 3.13t }]
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
          python-version: ${{ matrix.python }}

      - name: Remove C extension from pyproject.toml
        run: uv run disable_c_ext.py
        if: matrix.kind == 'pure-python'

      - name: Test
        run: uv run test.py -v
        env:
          PYTHONWARNINGS: ${{ matrix.kind == 'native' && 'error:Could not import cgeo C extension' || '' }}
