name: Release

on:
  workflow_dispatch:

jobs:
  package-version:
    name: Check package version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.package-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Get tag name from package version
        id: package-version
        run: |
          tag=v$(yq .project.version pyproject.toml)
          if [[ -n $(git tag -l "$tag") ]]; then
            echo "::error::Tag $tag already exists!"
            exit 1
          fi
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

  sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    needs: package-version
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Build sdist
        run: uv build --sdist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/

  pure-wheel:
    name: Build pure-python wheel
    runs-on: ubuntu-latest
    needs: package-version
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Remove C extension from pyproject.toml
        run: uv run disable_c_ext.py

      - name: Build wheel
        run: uv build --wheel

      - name: Test wheel
        run: uv run --directory ${{ runner.temp }} --with ${{ github.workspace }}/dist/*.whl ${{ github.workspace }}/test.py

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: pure-wheel
          path: dist/

  linux-wheels:
    name: Build wheels on Ubuntu
    runs-on: ubuntu-latest
    needs: package-version
    strategy:
      matrix:
        plat: [manylinux, musllinux]
        arch:
          - {cibw: x86_64}
          - {cibw: i686}
          - {cibw: aarch64, qemu: arm64}
          - {cibw: armv7l, qemu: arm}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch.qemu }}
        if: matrix.arch.qemu

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22
        env:
          CIBW_ARCHS: all
          CIBW_BUILD: cp*-${{ matrix.plat }}_${{ matrix.arch.cibw }}
          CIBW_ENABLE: cpython-freethreading
          CIBW_BUILD_FRONTEND: build[uv]
          CIBW_ENVIRONMENT: AUDITWHEEL_PLAT=

      - name: Upload wheels artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.plat }}-${{ matrix.arch.cibw }}-${{ strategy.job-index }}
          path: wheelhouse/

  windows-wheels:
    name: Build wheels on Windows
    runs-on: windows-latest
    needs: package-version
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.13t']
        arch: [x86_64, x86]
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: cpython-${{ matrix.python }}-windows-${{ matrix.arch }}
          enable-cache: false

      - name: Build wheel
        run: uv build --wheel

      - name: Install built wheel
        run: uv pip install --no-index -f dist -v zeevro-cgeo

      - name: Test wheel
        run: uv run --no-sync test.py -v
        env:
          PYTHONWARNINGS: error:Could not import cgeo C extension

      - name: Upload wheels artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-windows-${{ matrix.python }}-${{ matrix.arch }}-${{ strategy.job-index }}
          path: dist/

  macos-wheels:
    name: Build wheels on MacOS
    runs-on: macos-latest
    needs: package-version
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22
        env:
          CIBW_BUILD: cp*
          CIBW_ENABLE: cpython-freethreading
          CIBW_ARCHS: all
          CIBW_BUILD_FRONTEND: build[uv]
          CIBW_TEST_SKIP: '*arm64'

      - name: Upload wheels artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-macos
          path: wheelhouse/

  release:
    name: Release
    needs: [package-version, sdist, pure-wheel, linux-wheels, windows-wheels, macos-wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Create release
        run: gh release create --target ${{ github.sha }} --generate-notes ${{ needs.package-version.outputs.tag }} ./dist/*
        env:
          GITHUB_TOKEN: ${{ github.token }}

  publish:
    name: Publish
    needs: [sdist, pure-wheel, linux-wheels, windows-wheels, macos-wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/zeevro-cgeo
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Publish to PyPI
        run: uv publish
