name: Test Python fallback

run-name: ${{ github.workflow }} for ${{ github.ref }}

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-python-fallback:
    name: Test Python fallback on Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}-dev
          allow-prereleases: true

      - name: Test slow fallback
        run: python test.py
